# Generated by Django 3.1.5 on 2021-02-04 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approve',
            field=models.CharField(choices=[('a', 'approved'), ('d', 'Disapproved'), ('n', 'Not checked')], default='n', max_length=1),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 4, 21, 26, 28, 953814, tzinfo=utc))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 4, 21, 26, 28, 952816, tzinfo=utc))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
    ]
