# Generated by Django 3.1.6 on 2021-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20210205_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAdView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.view')),
            ],
            bases=('advertiser_management.view',),
        ),
    ]
